---
title: "Introducción"
---

La Sociedad para la Gestión Integrada del Riesgo de Desastres (IDRiM) se consolidó oficialmente el 15 de octubre de 2009 en Kioto, Japón. Desde entonces ha llevado a cabo la conferencia internacional en diferentes países, integrando a la comunidad científica interesada en la gestión integrada del riesgo de desastres a nivel mundial. En el año 2024 por primera vez la conferencia se organizó en América Latina, brindando una oportunidad única para reunir a expertos a nivel mundial en torno a la gestión integrada del riesgo de desastres y permitiendo su interacción. Es así como la Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD) organizó la 14° versión de la conferencia internacional anual IDRiM, en conjunto con la Sociedad IDRiM, la Universidad de Kioto y el Instituto de Investigación para la Prevención de Desastres (DPRI por sus siglas en inglés).

Cartagena de Indias fue el epicentro de esta 14° versión de la Conferencia titulada "Comunidades resilientes a los desastres por la vida. Este enfoque de la conferencia refleja la visión general del gobierno "Colombia, potencia mundial de la vida", la cual pretende sentar las bases para que Colombia emerja como líder global en la búsqueda colectiva de la vida, la humanidad, y la naturaleza.

La conferencia tuvo un enfoque amplio en la prevención y mitigación integrada de desastres, la respuesta de emergencias y la recuperación de desastres. Exhortó a la comunidad científica a considerar nuevas perspectivas más allá de los conceptos tradicionales de gestión de riesgos, que parecen insuficientes para abordar los riesgos e incertidumbres emergentes. Programada durante dos días y medio, del 28 al 30 de agosto, la conferencia proporcionó una plataforma colaborativa para el intercambio de conocimientos. IDRiM2024 en Cartagena fue un espacio único para fomentar el diálogo y compartir experiencias en el campo. Bajo el lema de IDRiM, "Yo sueño, tú sueñas, todos soñamos por un mundo más seguro", 2024 fue el año en que Colombia visualizó un país y una región más seguros e integrados.

Dentro de los asistentes se incluyeron investigadores, académicos, profesionales de la industria, estudiantes de pregrado y posgrado, funcionarios públicos, colaboradores de entidades gubernamentales, organizaciones no gubernamentales, planificadores y líderes. También contamos con la participación de la comunidad local y regional. Los participantes presentaron sus trabajos en sesiones paralelas, pósters y sesiones especiales. En esta ocasión se logró la asistencia más alta en la historia de la conferencia, sentando un precedente para los futuros encuentros. IDRiM2024 se consolida, como la versión más exitosa y con mayor participación de diversos actores, permitiendo una interacción nutrida y enriquecedora.