---
title: "Página legal"
---

© 2025 Unidad Nacional para la Gestión del Riesgo de Desastres. Todos los derechos reservados.

Unidad Nacional para la Gestión del Riesgo de Desastres
Calle 26 \# 92 - 32, Edificio Gold 4 - Piso 2
Bogotá, febrero de 2025
[www.gestiondelriesgo.gov.co](https://www.gestiondelriesgo.gov.co)

## Editores

-   Ana Milena Prada
-   Ana María Cruz
-   María Camila Suárez Paba
-   Mauricio Romero Torres
-   Luisa Cadena
-   Diana Mancera

## Diseño gráfico de la conferencia

-   Cristian Mendoza
-   Diana Sarmiento
-   Juan López Gómez

## ORGANIZADORES

**Presidente de la conferencia**

Carlos Alberto Carrillo Arenas

Director General UNGRD

## Comité organizador local

**Ana Milena Prada Uribe** Subdirectora para el Conocimiento del Riesgo UNGRD

**Rafael Enrique Cruz Rodríguez** Subdirector General UNGRD

**Subdirección para el Conocimiento del Riesgo** - *María Camila Suarez Paba* - *Mauricio Romero Torres* - *Valentina Rico* - *Brahan García* - *Diana Katherin Sarmiento Olave* - *Jeisson Orlando García*

## Comité organizador de la Sociedad IDRiM

**Ana María Cruz** Presidente Sociedad IDRiM

**Hirokazu Tatano** Vicepresidente Sociedad IDRiM

-   Zoltán Török, Babes-Bolyai University
-   Cluj-Napoca, Romania
-   Andrew Collins, Northumbria Unviersity
-   Elisabeth Krausmann, EC-JRC
-   Adam Rose, University of Southern California
-   Norio Okada, Kwansei Gakuin University
-   Muneta Yokomatsu, IIASA
-   Miranda Dandoulaki, Horokopion University of Athens, Greece
-   Sumit Sen, IIT
-   Subhajyoti Samaddar, Kyoto University
-   Genta Nakano, Kyoto University
-   Mark Ashley Parry, Northumbria Unviersity
-   Haris Rahadianto, Kyoto University
-   Masamitsu Onishi, Kyoto University
-   Hamilton Bean, University of Colorado Denver
-   James Goltz, University of Colorado Boulder, USA
-   Siva Srikrishnan, IIT

# Comité Científico

-   Nicolae Ajtai 
-   David Alexander 
-   Jorge Alpala 
-   Rafael Amaya
-   Mohsen Ashtiany 
-   Funda Atun 
-   Joanne Bayer 
-   Hamilton Bean 
-   Luisa Cadena 
-   Dorotea Cardona
-   Laura Carrero 
-   Ilan Chabay 
-   Andrew Collins 
-   Ana Maria Cruz 
-   Miranda Dandoulaki 
-   Lina Dorado 
-   Christian Euscátegui
-   Carlos A. García
-   Kyriaki Gkoktsi 
-   Robert Goble 
-   James Goltz 
-   Julio González 
-   Michinori Hatayama 
-   Nelson Hernández
-   Kaori Kitagawa 
-   Elisabeth Krausmann 
-   Evelin Langebeck 
-   Sandra Martínez
-   Yoko Matsuda
-   Sandra Mendoza 
-   Genta Nakano 
-   Norio Okada 
-   Makoto Okumura 
-   Masamitsu Onishi 
-   Vivian Olarte
-   Alexandru Ozunu 
-   Nicola Paltrinieri 
-   Beatriz Parra
-   Mark A. Parry
-   Joana Pérez 
-   Paola Quintero
-   Ágoston Restás 
-   Flover Rodríguez 
-   Mauricio Romero 
-   Subhajyoti Samaddar 
-   Laura Sánchez
-   Mauricio Sánchez 
-   Sumit Sen 
-   María Camila Suárez 
-   Hirokazu Tatano 
-   Zoltán TÖRÖK 
-   Jairo Valcárcel
-   Yoshiyuki Yama 
-   Katsuya Yamori 
-   Muneta Yokomatsu