---
title: "Sesión 2. Comunicación y educación en GRD"
---

## Resúmenes

1. [Estudio de materiales de aprendizaje sobre prevención de desastres utilizando registros históricos de desastres](charla-01/index.qmd)
2. [Una revisión de lo que importa en la educación sobre el cambio climático basada en experiencias en Inglaterra](charla-02/index.qmd)
3. [Incorporación de la gestión del riesgo y cambio climático en el currículo escolar, Institución Educativa San Bartolomé de La Florida (N) 2006-2024](charla-03/index.qmd)
4. [Estrategias educativas para la gestión del riesgo de desastres en la Universidad Pedagógica Nacional sede Kennedy en Bogotá Colombia](charla-04/index.qmd)
5. [El potencial de las cartas como herramienta de comunicación para la prevención de desastres](charla-05/index.qmd)
6. [La educación temprana en gestión del riesgo la clave para una sensibilización real](charla-06/index.qmd)

## Video de la sesión

<iframe src="https://drive.google.com/file/d/1WKv3_XQMvCNRqGZQdD43fgDGH5oKzC7b/preview" width="100%" height="480" allow="autoplay" allowfullscreen></iframe>

