---
title: "Sesión 20. Capacidad adaptativa y reducción de la vulnerabilidad ante riesgos ambientales y climáticos"
---

## Resúmenes

1. [Medición y comprensión del conocimiento ambiental en la conservación de los servicios ecosistémicos](charla-01/index.qmd)
2. [Desarrollo de capacidades para la reducción del riesgo de desastres en el entorno construido en América Latina y el Caribe (BERLAC)](charla-02/index.qmd)
3. [Gestión del riesgo orientada a la sostenibilidad: una ruta para mejorar la calidad de vida en las pequeñas ciudades](charla-03/index.qmd)
4. [Desafíos de la Adaptación Costera: Enfoque Basado en Ecosistemas en el Caribe Colombiano](charla-04/index.qmd)
5. [Viviendas de producción social ingobernables, tres décadas de exclusión](charla-05/index.qmd)
6. [Evaluación del efecto dominó de la pérdida de capacidad de producción del lado de la oferta causada por los peligros compuestos: desastres por inundaciones y COVID-19-Tomando como ejemplo Enshi,](charla-06/index.qmd)
7. [Utilidad de los datos de vigilancia de enfermedades para mejorar la alerta temprana del brote de cólera en el suroeste de Camerún, 2018](charla-07/index.qmd)
8. [SIATA: dos décadas de innovación en alertas tempranas para Medellín y el Valle de Aburrá](charla-08/index.qmd)

## Video de la sesión

<iframe src="https://drive.google.com/file/d/12lTSKdX_k4_pfSVRhtJEZ2TSC6IjCCN2/preview" width="100%" height="480" allow="autoplay" allowfullscreen></iframe>

<iframe src="https://drive.google.com/file/d/1ImKYwBDFoT6f5nSMwN9mRw3cvv6zn-6M/preview" width="100%" height="480" allow="autoplay" allowfullscreen></iframe>

