---
title: "Sesión 1. Justicia climática, cambio climático y riesgos emergentes"
---

## Resúmenes

1. [Estudio preliminar de isotopía de aguas superficiales y suelos en el páramo de Chingaza y rio Bogotá](charla-01/index.qmd)
2. [Evolución y retos de la gestión del riesgo en los instrumentos de planificación territoriales de Colombia](charla-02/index.qmd)
3. [Evaluación del efecto del cambio climático en las inundaciones por ciclones tropicales en las islas de San Andrés, Providencia y Santa Catalina](charla-03/index.qmd)
4. [Simulación de crecidas y evaluación de medida tradicional de control de inundaciones: el caso del delta del río Ranchería](charla-04/index.qmd)
5. [Avances en la comprensión de la variación isotópica en la precipitación producto de los cambios climáticos](charla-05/index.qmd)
6. [Evaluación de Eventos de Inundación y Desabastecimiento Hídrico en la Cuenca del Río Bogotá Bajo Escenarios de Cambio Climático](charla-06/index.qmd)

## Video de la sesión

<iframe src="https://drive.google.com/file/d/18e2LYrDj5f1DWQti36HbdMiZ9nV1k-Ci/preview" width="100%" height="480" allow="autoplay" allowfullscreen></iframe>

